USE [master]
GO

/****** Object:  Database [PosterNew]    Script Date: 15.02.2023 19:23:59 ******/
CREATE DATABASE [PosterNew]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'PosterNew', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\PosterNew.mdf' , SIZE = 16384KB , MAXSIZE = 65536KB , FILEGROWTH = 2048KB )
 LOG ON 
( NAME = N'PosterNewLog', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\PosterNewLog.ldf' , SIZE = 4096KB , MAXSIZE = 16384KB , FILEGROWTH = 512KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [PosterNew].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [PosterNew] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [PosterNew] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [PosterNew] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [PosterNew] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [PosterNew] SET ARITHABORT OFF 
GO

ALTER DATABASE [PosterNew] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [PosterNew] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [PosterNew] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [PosterNew] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [PosterNew] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [PosterNew] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [PosterNew] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [PosterNew] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [PosterNew] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [PosterNew] SET  ENABLE_BROKER 
GO

ALTER DATABASE [PosterNew] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [PosterNew] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [PosterNew] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [PosterNew] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [PosterNew] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [PosterNew] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [PosterNew] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [PosterNew] SET RECOVERY FULL 
GO

ALTER DATABASE [PosterNew] SET  MULTI_USER 
GO

ALTER DATABASE [PosterNew] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [PosterNew] SET DB_CHAINING OFF 
GO

ALTER DATABASE [PosterNew] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [PosterNew] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [PosterNew] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [PosterNew] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [PosterNew] SET QUERY_STORE = OFF
GO

ALTER DATABASE [PosterNew] SET  READ_WRITE 
GO

