//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AN6cw
{
    using System;
    using System.Collections.Generic;
    
    public partial class BuyOrderDetails
    {
        public int DetailID { get; set; }
        public int OrderID { get; set; }
        public int CatalogID { get; set; }
        public int Amount { get; set; }
    }
}
