//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AN6cw
{
    using System;
    using System.Collections.Generic;
    
    public partial class Catalog
    {
        public int CatalogID { get; set; }
        public int CategoryID { get; set; }
        public int ManufacturerID { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> Price { get; set; }
    }
}
