//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AN6cw
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalaryRate
    {
        public int RateID { get; set; }
        public int EmployeeID { get; set; }
        public decimal MonthlyRate { get; set; }
    }
}
